#include <emscripten/bind.h>

#include <libde265/de265.h>

using namespace emscripten;

EMSCRIPTEN_BINDINGS(common)
{
    function("get_version", &de265_get_version_number);

    function("get_version_major", &de265_get_version_number_major);
    function("get_version_minor", &de265_get_version_number_minor);
    function("get_version_maintenance", &de265_get_version_number_maintenance);

    enum_<de265_error>("Error", enum_value_type::number)
        .value("OK", DE265_OK)
        .value("ERROR_NO_SUCH_FILE", DE265_ERROR_NO_SUCH_FILE)
        .value("ERROR_COEFFICIENT_OUT_OF_IMAGE_BOUNDS", DE265_ERROR_COEFFICIENT_OUT_OF_IMAGE_BOUNDS)
        .value("ERROR_CHECKSUM_MISMATCH", DE265_ERROR_CHECKSUM_MISMATCH)
        .value("ERROR_CTB_OUTSIDE_IMAGE_AREA", DE265_ERROR_CTB_OUTSIDE_IMAGE_AREA)
        .value("ERROR_OUT_OF_MEMORY", DE265_ERROR_OUT_OF_MEMORY)
        .value("ERROR_CODED_PARAMETER_OUT_OF_RANGE", DE265_ERROR_CODED_PARAMETER_OUT_OF_RANGE)
        .value("ERROR_IMAGE_BUFFER_FULL", DE265_ERROR_IMAGE_BUFFER_FULL)
        .value("ERROR_CANNOT_START_THREADPOOL", DE265_ERROR_CANNOT_START_THREADPOOL)
        .value("ERROR_LIBRARY_INITIALIZATION_FAILED", DE265_ERROR_LIBRARY_INITIALIZATION_FAILED)
        .value("ERROR_LIBRARY_NOT_INITIALIZED", DE265_ERROR_LIBRARY_NOT_INITIALIZED)
        .value("ERROR_WAITING_FOR_INPUT_DATA", DE265_ERROR_WAITING_FOR_INPUT_DATA)
        .value("ERROR_CANNOT_PROCESS_SEI", DE265_ERROR_CANNOT_PROCESS_SEI)
        .value("ERROR_PARAMETER_PARSING", DE265_ERROR_PARAMETER_PARSING)
        .value("ERROR_NO_INITIAL_SLICE_HEADER", DE265_ERROR_NO_INITIAL_SLICE_HEADER)
        .value("ERROR_PREMATURE_END_OF_SLICE", DE265_ERROR_PREMATURE_END_OF_SLICE)
        .value("ERROR_UNSPECIFIED_DECODING_ERROR", DE265_ERROR_UNSPECIFIED_DECODING_ERROR)
        .value("ERROR_NOT_IMPLEMENTED_YET", DE265_ERROR_NOT_IMPLEMENTED_YET)
        .value("WARNING_NO_WPP_CANNOT_USE_MULTITHREADING", DE265_WARNING_NO_WPP_CANNOT_USE_MULTITHREADING)
        .value("WARNING_WARNING_BUFFER_FULL", DE265_WARNING_WARNING_BUFFER_FULL)
        .value("WARNING_PREMATURE_END_OF_SLICE_SEGMENT", DE265_WARNING_PREMATURE_END_OF_SLICE_SEGMENT)
        .value("WARNING_INCORRECT_ENTRY_POINT_OFFSET", DE265_WARNING_INCORRECT_ENTRY_POINT_OFFSET)
        .value("WARNING_CTB_OUTSIDE_IMAGE_AREA", DE265_WARNING_CTB_OUTSIDE_IMAGE_AREA)
        .value("WARNING_SPS_HEADER_INVALID", DE265_WARNING_SPS_HEADER_INVALID)
        .value("WARNING_PPS_HEADER_INVALID", DE265_WARNING_PPS_HEADER_INVALID)
        .value("WARNING_SLICEHEADER_INVALID", DE265_WARNING_SLICEHEADER_INVALID)
        .value("WARNING_INCORRECT_MOTION_VECTOR_SCALING", DE265_WARNING_INCORRECT_MOTION_VECTOR_SCALING)
        .value("WARNING_NONEXISTING_PPS_REFERENCED", DE265_WARNING_NONEXISTING_PPS_REFERENCED)
        .value("WARNING_NONEXISTING_SPS_REFERENCED", DE265_WARNING_NONEXISTING_SPS_REFERENCED)
        .value("WARNING_BOTH_PREDFLAGS_ZERO", DE265_WARNING_BOTH_PREDFLAGS_ZERO)
        .value("WARNING_NONEXISTING_REFERENCE_PICTURE_ACCESSED", DE265_WARNING_NONEXISTING_REFERENCE_PICTURE_ACCESSED)
        .value("WARNING_NUMMVP_NOT_EQUAL_TO_NUMMVQ", DE265_WARNING_NUMMVP_NOT_EQUAL_TO_NUMMVQ)
        .value("WARNING_NUMBER_OF_SHORT_TERM_REF_PIC_SETS_OUT_OF_RANGE", DE265_WARNING_NUMBER_OF_SHORT_TERM_REF_PIC_SETS_OUT_OF_RANGE)
        .value("WARNING_SHORT_TERM_REF_PIC_SET_OUT_OF_RANGE", DE265_WARNING_SHORT_TERM_REF_PIC_SET_OUT_OF_RANGE)
        .value("WARNING_FAULTY_REFERENCE_PICTURE_LIST", DE265_WARNING_FAULTY_REFERENCE_PICTURE_LIST)
        .value("WARNING_EOSS_BIT_NOT_SET", DE265_WARNING_EOSS_BIT_NOT_SET)
        .value("WARNING_MAX_NUM_REF_PICS_EXCEEDED", DE265_WARNING_MAX_NUM_REF_PICS_EXCEEDED)
        .value("WARNING_INVALID_CHROMA_FORMAT", DE265_WARNING_INVALID_CHROMA_FORMAT)
        .value("WARNING_SLICE_SEGMENT_ADDRESS_INVALID", DE265_WARNING_SLICE_SEGMENT_ADDRESS_INVALID)
        .value("WARNING_DEPENDENT_SLICE_WITH_ADDRESS_ZERO", DE265_WARNING_DEPENDENT_SLICE_WITH_ADDRESS_ZERO)
        .value("WARNING_NUMBER_OF_THREADS_LIMITED_TO_MAXIMUM", DE265_WARNING_NUMBER_OF_THREADS_LIMITED_TO_MAXIMUM)
        .value("NON_EXISTING_LT_REFERENCE_CANDIDATE_IN_SLICE_HEADER", DE265_NON_EXISTING_LT_REFERENCE_CANDIDATE_IN_SLICE_HEADER)
        .value("WARNING_CANNOT_APPLY_SAO_OUT_OF_MEMORY", DE265_WARNING_CANNOT_APPLY_SAO_OUT_OF_MEMORY)
        .value("WARNING_SPS_MISSING_CANNOT_DECODE_SEI", DE265_WARNING_SPS_MISSING_CANNOT_DECODE_SEI)
        .value("WARNING_COLLOCATED_MOTION_VECTOR_OUTSIDE_IMAGE_AREA", DE265_WARNING_COLLOCATED_MOTION_VECTOR_OUTSIDE_IMAGE_AREA)
        .value("WARNING_PCM_BITDEPTH_TOO_LARGE", DE265_WARNING_PCM_BITDEPTH_TOO_LARGE)
        .value("WARNING_REFERENCE_IMAGE_BIT_DEPTH_DOES_NOT_MATCH", DE265_WARNING_REFERENCE_IMAGE_BIT_DEPTH_DOES_NOT_MATCH)
        .value("WARNING_REFERENCE_IMAGE_SIZE_DOES_NOT_MATCH_SPS", DE265_WARNING_REFERENCE_IMAGE_SIZE_DOES_NOT_MATCH_SPS)
        .value("WARNING_CHROMA_OF_CURRENT_IMAGE_DOES_NOT_MATCH_SPS", DE265_WARNING_CHROMA_OF_CURRENT_IMAGE_DOES_NOT_MATCH_SPS)
        .value("WARNING_BIT_DEPTH_OF_CURRENT_IMAGE_DOES_NOT_MATCH_SPS", DE265_WARNING_BIT_DEPTH_OF_CURRENT_IMAGE_DOES_NOT_MATCH_SPS)
        .value("WARNING_REFERENCE_IMAGE_CHROMA_FORMAT_DOES_NOT_MATCH", DE265_WARNING_REFERENCE_IMAGE_CHROMA_FORMAT_DOES_NOT_MATCH)
        .value("WARNING_INVALID_SLICE_HEADER_INDEX_ACCESS", DE265_WARNING_INVALID_SLICE_HEADER_INDEX_ACCESS);

    function("getErrorText(error)", +[](de265_error error)
                                    { return std::string(de265_get_error_text(error)); });

    function("isOk(error)", +[](de265_error error)
                            { return (bool)de265_isOK(error); });
}
